# Copyright 2018-2023 Chris Farris <chrisf@primeharbor.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates a cross account role for audit & security tool management from a dedicated security account

# TemplateSource: https://github.com/primeharbor/aws-account-automation/blob/master/cloudformation/AuditRole-Template.yaml

Parameters:

  TrustedAccountNumber:
    Description: The 12 digit AWS account number to grant access to.
    Default: '123456789012'
    MinLength: '12'
    AllowedPattern: '[0-9]+'
    MaxLength: '12'
    Type: String

  RoleName:
    Description: The name of the Audit Role to be created
    Default: 'security-audit'
    Type: String


Resources:
  AuditorCrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/SecurityAudit
      - arn:aws:iam::aws:policy/ReadOnlyAccess
      - arn:aws:iam::aws:policy/AWSAccountManagementReadOnlyAccess
      - arn:aws:iam::aws:policy/AWSSSOReadOnly
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: sts:AssumeRole
          Sid: ''
          Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${TrustedAccountNumber}:root"
      Policies:
        - PolicyName: MissingPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "iam:Simulate*"
                  - "account:GetContactInformation"
                  - "ecr:StartImageScan"
                  - "glue:GetConnections"
                  - "backup:ListReportPlans"
                Resource: "*"
        - PolicyName: SecurityAuditTools
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                - "trustedAdvisor:*"
                - "health:*"
                - "access-analyzer:*"
                - "macie:*"
                - "inspector:*"
                - "support:*"
                - "guardduty:*"
                - "securityhub:*"
                Resource: "*"
        - PolicyName: BillingAuditPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                - "aws-portal:View*" # Legacy Perm going away
                - "ce:*"             # Full Access to Cost Explorer
                - "account:Get*"
                - "billing:Get*"
                - "payments:List*"
                - "payments:Get*"
                - "tax:List*"
                - "tax:Get*"
                - "consolidatedbilling:Get*"
                - "consolidatedbilling:List*"
                - "invoicing:List*"
                - "invoicing:Get*"
                - "cur:Get*"
                - "cur:Validate*"
                - "freetier:Get*"
                Resource: "*"

Outputs:
  RoleARN:
    Description: The ARN of the Audit role that can be assumed by the other account.
    Value: !GetAtt AuditorCrossAccountRole.Arn

  TemplateVersion:
    Value: 1.3.2