# Copyright 2021-2023 Chris Farris <chrisf@primeharbor.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy the AWS Config Service Recorder in this region and send recorded events to central bucket
# TemplateSource: https://github.com/primeharbor/aws-account-automation/blob/master/cloudformation/AWSConfigRecorder-Template.yaml

Parameters:

  pOrganizationConfigBucket:
    Description: Name of the bucket where Config Events are stored.
    Type: String

  pAggregationRegion:
    Description: Region to authorize for a Config Aggregation (Set to NONE for no authorization)
    Default: NONE
    Type: String

Conditions:
  CreateAggregationAuthorization:  !Equals [ !Ref "AWS::Region", !Ref pAggregationRegion ]
  CreateServiceLinkedRole: !Equals [ !Ref "AWS::Region", "us-east-1"]
  cIncludeGlobalResourceTypes: !Equals [ !Ref "AWS::Region", "us-east-1"]

Resources:

  ConfigTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Sub "ConfigTopic-${AWS::Region}"
      DisplayName: Local AWS Config Notification Topic
      KmsMasterKeyId: "alias/aws/sns"

  ConfigTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref ConfigTopic
      PolicyDocument:
        Statement:
          - Sid: AWSConfigSNSPolicy
            Action:
              - sns:Publish
            Effect: Allow
            Resource: !Ref ConfigTopic
            Principal:
              Service:
                - config.amazonaws.com

  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      Name: default
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: !If [ cIncludeGlobalResourceTypes, True, False ]
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/config.amazonaws.com/AWSServiceRoleForConfig'

  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Properties:
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: Six_Hours
      S3BucketName: !Ref pOrganizationConfigBucket
      SnsTopicARN: !Ref 'ConfigTopic'

  AWSServiceRoleForConfig:
    Type: AWS::IAM::ServiceLinkedRole
    Condition: CreateServiceLinkedRole
    Properties:
      AWSServiceName: config.amazonaws.com

  # Why they don't have a service linked role here is beyond me
  ConfigAggregatorRole:
    Condition: CreateAggregationAuthorization
    Type: AWS::IAM::Role
    Properties:
      # RoleName: !Sub "aws-config-aggregator-role-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSConfigRoleForOrganizations

  # Create the Aggregator
  ConfigAggregator:
    Type: AWS::Config::ConfigurationAggregator
    Condition: CreateAggregationAuthorization
    Properties:
      ConfigurationAggregatorName: !Sub "${AWS::StackName}-Aggregator"
      OrganizationAggregationSource:
          AllAwsRegions: True
          RoleArn: !GetAtt ConfigAggregatorRole.Arn


Outputs:
  ConfigTopicArn:
    Value: !Ref ConfigTopic
  TemplateVersion:
    Value: "1.1.1"
